/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author salaheddine
 */
public class JFrameGUI extends javax.swing.JFrame {

    /**
     * Creates new form JFrameGUI
     */
    
    public JPanel addCenterPanel = new JPanel();
    public static JFrameGUI frame = new JFrameGUI();
    
    
    public JFrameGUI() {
        
        
    }
    
    public JFrameGUI(int start) {
        
        initComponents();
        this.setSize(new Dimension(500, 584));
        CenterPanel();
        
        frame=this;
        
        System.out.println("First size : "+this.getSize());
        
        
    }
    
    
    
    public void CenterPanel(){
        
        addCenterPanel.setVisible(true);
        
        addCenterPanel.setLayout(new BorderLayout());
       
        
        /////***** Creation d'un Objet de type classe JPanel ******//////
        CenterPanel addbody = new CenterPanel();
        /////***** Appel au Constricteur Surcharger de la classe JPanal et le REVALIDER *****//////
        addbody.CenterPanel(addCenterPanel).revalidate();
        
        /////***** Fixé la taille du Zone où le nouveau JPanel sera placer dans JFrame *****//////
        
        jPanelBaseCenter.setLayout(new BorderLayout());
        jPanelBaseCenter.add(addCenterPanel, java.awt.BorderLayout.CENTER);
	/////***** Refaire le dessin de la JFrame ******//////
        this.repaint();
        /////***** Afficher la JFrame ******//////
        setVisible(true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFooter = new javax.swing.JPanel();
        jPanelCoinG = new javax.swing.JPanel();
        jLabelCoinG = new javax.swing.JLabel();
        jPanelCoinD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelFooterCenter = new javax.swing.JPanel();
        jPanelFL = new javax.swing.JPanel();
        jPanelFC = new javax.swing.JPanel();
        jLabelCopyright = new javax.swing.JLabel();
        jPanelFR = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jPanelCoinTopG = new javax.swing.JPanel();
        jLabelCoinTopG = new javax.swing.JLabel();
        jPanelCoinTopD = new javax.swing.JPanel();
        jLabelCoinTopD = new javax.swing.JLabel();
        jPanelHeaderCenter = new javax.swing.JPanel();
        jPanelBaseCenter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 584));

        jPanelFooter.setMinimumSize(new java.awt.Dimension(100, 32));
        jPanelFooter.setOpaque(false);
        jPanelFooter.setPreferredSize(new java.awt.Dimension(977, 32));
        jPanelFooter.setLayout(new java.awt.BorderLayout());

        jPanelCoinG.setLayout(new java.awt.BorderLayout());

        jLabelCoinG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/theme/coing.png"))); // NOI18N
        jPanelCoinG.add(jLabelCoinG, java.awt.BorderLayout.CENTER);

        jPanelFooter.add(jPanelCoinG, java.awt.BorderLayout.WEST);

        jPanelCoinD.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/theme/coind.png"))); // NOI18N
        jPanelCoinD.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanelFooter.add(jPanelCoinD, java.awt.BorderLayout.EAST);

        jPanelFooterCenter.setBackground(new java.awt.Color(235, 235, 235));
        jPanelFooterCenter.setLayout(new java.awt.BorderLayout());

        jPanelFL.setOpaque(false);
        jPanelFL.setPreferredSize(new java.awt.Dimension(138, 32));

        javax.swing.GroupLayout jPanelFLLayout = new javax.swing.GroupLayout(jPanelFL);
        jPanelFL.setLayout(jPanelFLLayout);
        jPanelFLLayout.setHorizontalGroup(
            jPanelFLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelFLLayout.setVerticalGroup(
            jPanelFLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFooterCenter.add(jPanelFL, java.awt.BorderLayout.WEST);

        jPanelFC.setOpaque(false);
        jPanelFC.setLayout(new java.awt.BorderLayout());

        jLabelCopyright.setText("Copyright © 2015 BDSas. All rights reserved. Devlopped by SALAH EDDINE RAMAH.");
        jPanelFC.add(jLabelCopyright, java.awt.BorderLayout.CENTER);

        jPanelFooterCenter.add(jPanelFC, java.awt.BorderLayout.CENTER);

        jPanelFR.setOpaque(false);
        jPanelFR.setPreferredSize(new java.awt.Dimension(138, 32));

        javax.swing.GroupLayout jPanelFRLayout = new javax.swing.GroupLayout(jPanelFR);
        jPanelFR.setLayout(jPanelFRLayout);
        jPanelFRLayout.setHorizontalGroup(
            jPanelFRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPanelFRLayout.setVerticalGroup(
            jPanelFRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanelFooterCenter.add(jPanelFR, java.awt.BorderLayout.EAST);

        jPanelFooter.add(jPanelFooterCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelFooter, java.awt.BorderLayout.PAGE_END);

        jPanelHeader.setMinimumSize(new java.awt.Dimension(86, 32));
        jPanelHeader.setOpaque(false);
        jPanelHeader.setPreferredSize(new java.awt.Dimension(977, 32));
        jPanelHeader.setLayout(new java.awt.BorderLayout());

        jPanelCoinTopG.setOpaque(false);
        jPanelCoinTopG.setLayout(new java.awt.BorderLayout());

        jLabelCoinTopG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/theme/cointg.png"))); // NOI18N
        jPanelCoinTopG.add(jLabelCoinTopG, java.awt.BorderLayout.CENTER);

        jPanelHeader.add(jPanelCoinTopG, java.awt.BorderLayout.WEST);

        jPanelCoinTopD.setOpaque(false);
        jPanelCoinTopD.setLayout(new java.awt.BorderLayout());

        jLabelCoinTopD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/theme/cointd.png"))); // NOI18N
        jPanelCoinTopD.add(jLabelCoinTopD, java.awt.BorderLayout.CENTER);

        jPanelHeader.add(jPanelCoinTopD, java.awt.BorderLayout.EAST);

        jPanelHeaderCenter.setBackground(new java.awt.Color(235, 235, 235));

        javax.swing.GroupLayout jPanelHeaderCenterLayout = new javax.swing.GroupLayout(jPanelHeaderCenter);
        jPanelHeaderCenter.setLayout(jPanelHeaderCenterLayout);
        jPanelHeaderCenterLayout.setHorizontalGroup(
            jPanelHeaderCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        jPanelHeaderCenterLayout.setVerticalGroup(
            jPanelHeaderCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanelHeader.add(jPanelHeaderCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelHeader, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanelBaseCenterLayout = new javax.swing.GroupLayout(jPanelBaseCenter);
        jPanelBaseCenter.setLayout(jPanelBaseCenterLayout);
        jPanelBaseCenterLayout.setHorizontalGroup(
            jPanelBaseCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 977, Short.MAX_VALUE)
        );
        jPanelBaseCenterLayout.setVerticalGroup(
            jPanelBaseCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelBaseCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGUI(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCoinG;
    private javax.swing.JLabel jLabelCoinTopD;
    private javax.swing.JLabel jLabelCoinTopG;
    private javax.swing.JLabel jLabelCopyright;
    private javax.swing.JPanel jPanelBaseCenter;
    private javax.swing.JPanel jPanelCoinD;
    private javax.swing.JPanel jPanelCoinG;
    private javax.swing.JPanel jPanelCoinTopD;
    private javax.swing.JPanel jPanelCoinTopG;
    private javax.swing.JPanel jPanelFC;
    private javax.swing.JPanel jPanelFL;
    private javax.swing.JPanel jPanelFR;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelFooterCenter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelHeaderCenter;
    // End of variables declaration//GEN-END:variables
}
